///
///	This file has been generated by bvtidl.pl. DO NOT MODIFY!
///

namespace BVTSDK {
	public enum AddressMode{
		DHCP_Client = 1,
		Static = 2,
	};

	public enum LogLevel{
		None = -1,
		Critical = 0,
		Warning = 1,
		Status = 2,
	};

	public enum FluidType{
		Saltwater = 0,
		Freshwater = 1,
		Other = 2,
	};

	public enum ImageRes{
		Off = 0,
		Low = 1,
		Medium = 2,
		High = 3,
		Auto = 4,
	};

	public enum ImageType{
		XY = 0,
		RTHETA = 1,
	};

	public enum ImageFilterFlags{
		None = 0,
		Mean3x3 = 2,
		Mean9x2 = 16,
	};

	public enum ImageProcessingMethod{
		A = 0,
		B = 1,
	};

	public enum MountType{
		Unknown = 0,
		Pole = 1,
		Tripod = 2,
		ROV = 3,
		UUV = 4,
		Other = 5,
	};

	public enum MountSide{
		Unknown = 0,
		Port = 1,
		Starboard = 2,
		Dorsal = 3,
		Ventral = 4,
		Bow = 5,
		Stern = 6,
		Other = 7,
	};

	public enum TriggerOutputEvent{
		StartOfTransmit = 0,
		EndOfTransmit = 1,
		EndOfAcquisition = 2,
	};

}
